#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

PYTHON_BIN="${PYTHON_BIN:-/root/miniconda3/envs/navsim/bin/python}"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-/mnt/project/VLA-AD}"
RUN_NAME="${RUN_NAME:-stage3_grpo_rpp_constrained_s16_lr1e4_b2acc4_$(date -u +%Y%m%dT%H%M%SZ)}"
OUT_ROOT="${OUT_ROOT:-${ARTIFACT_ROOT}/outputs/${RUN_NAME}}"

# This launcher intentionally keeps the algorithmic variable narrow:
# mature ReCogDrive-91 style RPP/GRPO recipe plus explicit TTC/DDC guards.
export CACHE_MODE="${CACHE_MODE:-online}"
export KILL_GPU_STRESS="${KILL_GPU_STRESS:-0}"
export GPU_LIST="${GPU_LIST:-0,1,2,3,4,5,6,7}"
export GPUS_PER_NODE="${GPUS_PER_NODE:-8}"
export DDP_STRATEGY="${DDP_STRATEGY:-ddp}"
export CUDA_LAUNCH_BLOCKING="${CUDA_LAUNCH_BLOCKING:-0}"

export LR="${LR:-1e-4}"
export STAGE3_OBJECTIVE="${STAGE3_OBJECTIVE:-none}"
export MAX_EPOCHS="${MAX_EPOCHS:-20}"
export BATCH_SIZE="${BATCH_SIZE:-2}"
export ACCUMULATE_GRAD_BATCHES="${ACCUMULATE_GRAD_BATCHES:-4}"
export GRPO_SAMPLE_TIME="${GRPO_SAMPLE_TIME:-16}"
export BC_ANNEAL="${BC_ANNEAL:-true}"
export BC_COEFF_START="${BC_COEFF_START:-0.10}"
export BC_COEFF_END="${BC_COEFF_END:-0.05}"
export BC_ANNEAL_EPOCHS="${BC_ANNEAL_EPOCHS:-5}"
export REFERENCE_KL_COEFF="${REFERENCE_KL_COEFF:-0.02}"
export REFERENCE_KL_CHUNK_SIZE="${REFERENCE_KL_CHUNK_SIZE:-0}"

# Match the successful 91.04 Reinforce++ property: group de-centering followed
# by batch-level advantage normalization. Keep GSPO/PPO replay off for this run.
export GRPO_USE_GSPO_RATIO="${GRPO_USE_GSPO_RATIO:-false}"
export GRPO_NORMALIZE_ADVANTAGE_BATCH="${GRPO_NORMALIZE_ADVANTAGE_BATCH:-true}"
export GRPO_ADVANTAGE_CLIP_ABS="${GRPO_ADVANTAGE_CLIP_ABS:-5.0}"

# 91.04 improved EP/DAC/TTC but regressed DDC. Constrain the positive policy
# update to trajectories that preserve TTC/DDC instead of only optimizing PDMS.
export GRPO_HARD_GATE_TTC="${GRPO_HARD_GATE_TTC:-true}"
export GRPO_HARD_GATE_DDC="${GRPO_HARD_GATE_DDC:-true}"
export GRPO_TTC_SAFE_THRESHOLD="${GRPO_TTC_SAFE_THRESHOLD:-0.95}"
export GRPO_DDC_SAFE_THRESHOLD="${GRPO_DDC_SAFE_THRESHOLD:-0.99}"

export GRPO_SCHEDULER_EPOCHS="${GRPO_SCHEDULER_EPOCHS:-${MAX_EPOCHS}}"
export GRPO_SCHEDULER_WARMUP_EPOCHS="${GRPO_SCHEDULER_WARMUP_EPOCHS:-0}"
export GRPO_SCHEDULER_MIN_LR="${GRPO_SCHEDULER_MIN_LR:-1e-5}"
export CHECKPOINT_EVERY_N_EPOCHS="${CHECKPOINT_EVERY_N_EPOCHS:-1}"
export CHECKPOINT_EVERY_N_TRAIN_STEPS="${CHECKPOINT_EVERY_N_TRAIN_STEPS:-300}"

# Keep buffer/DPO/self-imitation disabled in this control. Buffer absorption
# remains a separate experiment.
export OFFLINE_RL_ENABLED="${OFFLINE_RL_ENABLED:-false}"
export GRPO_BUFFER_GUIDANCE_ENABLED="${GRPO_BUFFER_GUIDANCE_ENABLED:-false}"
export GRPO_BUFFER_REWARD_BONUS_WEIGHT="${GRPO_BUFFER_REWARD_BONUS_WEIGHT:-0.0}"
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT="${GRPO_BUFFER_DISTILL_LOSS_WEIGHT:-0.0}"
export GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT="${GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT:-0.0}"
export GRPO_SELF_IMITATION_LOSS_WEIGHT="${GRPO_SELF_IMITATION_LOSS_WEIGHT:-0.0}"

export TRAIN_WAIT_FOR_FREE_GPUS="${TRAIN_WAIT_FOR_FREE_GPUS:-0}"
export TRAIN_GPU_MAX_MEM_USED_MB="${TRAIN_GPU_MAX_MEM_USED_MB:-65000}"
export TRAIN_GPU_MAX_UTIL="${TRAIN_GPU_MAX_UTIL:-101}"
export START_EARLY_GATE_WATCHER="${START_EARLY_GATE_WATCHER:-1}"
export EARLY_GATE_THRESHOLD="${EARLY_GATE_THRESHOLD:-0.88}"
export EARLY_GATE_MARGIN="${EARLY_GATE_MARGIN:-0.005}"
export EARLY_GATE_STOP_ON_FAIL="${EARLY_GATE_STOP_ON_FAIL:-0}"
export EARLY_GATE_MIN_STOP_STEP="${EARLY_GATE_MIN_STOP_STEP:-3000}"

export RUN_TRAIN="${RUN_TRAIN:-1}"
export LAUNCH_EVAL_WATCHERS="${LAUNCH_EVAL_WATCHERS:-1}"
export PRIMARY_EVAL_HOST="${PRIMARY_EVAL_HOST:-training-vla-zt2}"
export SECONDARY_EVAL_HOST="${SECONDARY_EVAL_HOST:-}"
export EVAL_WAIT_FOR_FREE_GPUS="${EVAL_WAIT_FOR_FREE_GPUS:-1}"
export EVAL_GPU_MAX_MEM_USED_MB="${EVAL_GPU_MAX_MEM_USED_MB:-65000}"
export EVAL_GPU_MAX_UTIL="${EVAL_GPU_MAX_UTIL:-101}"

exec "${REPO_ROOT}/scripts/training/launch_recogdrive_stage3_grpo_gspo_2b_local_stable.sh"
