#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

PYTHON_BIN="${PYTHON_BIN:-/root/miniconda3/envs/navsim/bin/python}"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-/mnt/project/VLA-AD}"
RUN_NAME="${RUN_NAME:-stage3_grpo_softsafety_selfimit_s16_lr1e4_b2acc4_$(date -u +%Y%m%dT%H%M%SZ)}"
OUT_ROOT="${OUT_ROOT:-${ARTIFACT_ROOT}/outputs/${RUN_NAME}}"

# Evidence basis:
# - cap05 self-imitation beat the current-repo GRPO control at matched step300
#   and step900, but it traded EP gains against NC/TTC/DDC regressions.
# - main hard TTC/DDC gating underperformed at matched early steps because it
#   suppressed progress too strongly.
# This recipe preserves the cap05 absorption path and replaces main hard
# TTC/DDC gating with a continuous TTC/DDC safety penalty.
export CACHE_MODE="${CACHE_MODE:-online}"
export KILL_GPU_STRESS="${KILL_GPU_STRESS:-0}"
export GPU_LIST="${GPU_LIST:-0,1,2,3,4,5,6,7}"
export GPUS_PER_NODE="${GPUS_PER_NODE:-8}"
export DDP_STRATEGY="${DDP_STRATEGY:-ddp}"

export LR="${LR:-1e-4}"
export STAGE3_OBJECTIVE="${STAGE3_OBJECTIVE:-none}"
export MAX_EPOCHS="${MAX_EPOCHS:-20}"
export BATCH_SIZE="${BATCH_SIZE:-2}"
export ACCUMULATE_GRAD_BATCHES="${ACCUMULATE_GRAD_BATCHES:-4}"
export CHECKPOINT_EVERY_N_EPOCHS="${CHECKPOINT_EVERY_N_EPOCHS:-1}"
export CHECKPOINT_EVERY_N_TRAIN_STEPS="${CHECKPOINT_EVERY_N_TRAIN_STEPS:-300}"

export GRPO_SAMPLE_TIME="${GRPO_SAMPLE_TIME:-16}"
export BC_ANNEAL="${BC_ANNEAL:-true}"
export BC_COEFF_START="${BC_COEFF_START:-0.10}"
export BC_COEFF_END="${BC_COEFF_END:-0.05}"
export BC_ANNEAL_EPOCHS="${BC_ANNEAL_EPOCHS:-5}"
export REFERENCE_KL_COEFF="${REFERENCE_KL_COEFF:-0.02}"
export REFERENCE_KL_CHUNK_SIZE="${REFERENCE_KL_CHUNK_SIZE:-16}"

export GRPO_USE_GSPO_RATIO="${GRPO_USE_GSPO_RATIO:-true}"
export GRPO_GSPO_CLIP_LOW="${GRPO_GSPO_CLIP_LOW:-0.05}"
export GRPO_GSPO_CLIP_HIGH="${GRPO_GSPO_CLIP_HIGH:-0.05}"
export GRPO_BEHAVIOR_POLICY_SYNC_INTERVAL="${GRPO_BEHAVIOR_POLICY_SYNC_INTERVAL:-4}"
export GRPO_BEHAVIOR_POLICY_SAMPLE="${GRPO_BEHAVIOR_POLICY_SAMPLE:-true}"
export GRPO_NORMALIZE_ADVANTAGE_BATCH="${GRPO_NORMALIZE_ADVANTAGE_BATCH:-false}"
export GRPO_ADVANTAGE_CLIP_ABS="${GRPO_ADVANTAGE_CLIP_ABS:-0.0}"

export GRPO_HARD_GATE_TTC="${GRPO_HARD_GATE_TTC:-false}"
export GRPO_HARD_GATE_DDC="${GRPO_HARD_GATE_DDC:-false}"
export GRPO_SAFETY_ADVANTAGE_MODE="${GRPO_SAFETY_ADVANTAGE_MODE:-soft_penalty}"
export GRPO_TTC_SAFE_THRESHOLD="${GRPO_TTC_SAFE_THRESHOLD:-0.95}"
export GRPO_DDC_SAFE_THRESHOLD="${GRPO_DDC_SAFE_THRESHOLD:-0.99}"
export GRPO_SOFT_SAFETY_PENALTY_WEIGHT="${GRPO_SOFT_SAFETY_PENALTY_WEIGHT:-0.50}"
export GRPO_SOFT_SAFETY_PENALTY_CLIP="${GRPO_SOFT_SAFETY_PENALTY_CLIP:-0.50}"
export GRPO_SOFT_SAFETY_MIN_REWARD="${GRPO_SOFT_SAFETY_MIN_REWARD:-0.0}"

export GRPO_SCHEDULER_EPOCHS="${GRPO_SCHEDULER_EPOCHS:-${MAX_EPOCHS}}"
export GRPO_SCHEDULER_WARMUP_EPOCHS="${GRPO_SCHEDULER_WARMUP_EPOCHS:-0}"
export GRPO_SCHEDULER_MIN_LR="${GRPO_SCHEDULER_MIN_LR:-1e-5}"

export OFFLINE_RL_ENABLED="${OFFLINE_RL_ENABLED:-true}"
export ELITE_BUFFER_DIR="${ELITE_BUFFER_DIR:-${ARTIFACT_ROOT}/cache/recogdrive_stage3_awac_elite_buffer_train_v2_stage3_awac_iql_dualhost_20260612T182947Z}"
export OFFLINE_RL_CACHE_ELITE_RECORDS_IN_MEMORY="${OFFLINE_RL_CACHE_ELITE_RECORDS_IN_MEMORY:-true}"
export OFFLINE_RL_STRICT_REWARD_SUBMETRICS="${OFFLINE_RL_STRICT_REWARD_SUBMETRICS:-true}"
export OFFLINE_RL_MISSING_SUBMETRIC_POLICY="${OFFLINE_RL_MISSING_SUBMETRIC_POLICY:-error}"
export OFFLINE_RL_USE_BATCHED_PDM_SCORING="${OFFLINE_RL_USE_BATCHED_PDM_SCORING:-true}"
export OFFLINE_RL_USE_EXACT_ARRAY_PDM_STATE_CONVERSION="${OFFLINE_RL_USE_EXACT_ARRAY_PDM_STATE_CONVERSION:-true}"
export OFFLINE_RL_USE_FAST_PDM_SCORER="${OFFLINE_RL_USE_FAST_PDM_SCORER:-true}"
export OFFLINE_RL_PDM_SHADOW_CHECK="${OFFLINE_RL_PDM_SHADOW_CHECK:-false}"

export GRPO_BUFFER_GUIDANCE_ENABLED="${GRPO_BUFFER_GUIDANCE_ENABLED:-true}"
export GRPO_BUFFER_REWARD_BONUS_WEIGHT="${GRPO_BUFFER_REWARD_BONUS_WEIGHT:-0.0}"
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT="${GRPO_BUFFER_DISTILL_LOSS_WEIGHT:-0.01}"
export GRPO_BUFFER_DISTILL_LOSS_SCHEDULE="${GRPO_BUFFER_DISTILL_LOSS_SCHEDULE:-linear_warmup}"
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT_START="${GRPO_BUFFER_DISTILL_LOSS_WEIGHT_START:-0.0}"
export GRPO_BUFFER_DISTILL_WARMUP_START_EPOCH="${GRPO_BUFFER_DISTILL_WARMUP_START_EPOCH:-0}"
export GRPO_BUFFER_DISTILL_WARMUP_EPOCHS="${GRPO_BUFFER_DISTILL_WARMUP_EPOCHS:-4}"
export GRPO_BUFFER_DISTILL_TOP_K="${GRPO_BUFFER_DISTILL_TOP_K:-1}"
export GRPO_BUFFER_DISTILL_MIN_REWARD_MARGIN="${GRPO_BUFFER_DISTILL_MIN_REWARD_MARGIN:-0.02}"
export GRPO_BUFFER_DISTILL_TIMESTEP_SAMPLING="${GRPO_BUFFER_DISTILL_TIMESTEP_SAMPLING:-low_noise}"
export GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT="${GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT:-0.0}"

export GRPO_SELF_IMITATION_LOSS_WEIGHT="${GRPO_SELF_IMITATION_LOSS_WEIGHT:-0.01}"
export GRPO_SELF_IMITATION_LOSS_SCHEDULE="${GRPO_SELF_IMITATION_LOSS_SCHEDULE:-linear_warmup}"
export GRPO_SELF_IMITATION_LOSS_WEIGHT_START="${GRPO_SELF_IMITATION_LOSS_WEIGHT_START:-0.0}"
export GRPO_SELF_IMITATION_WARMUP_START_EPOCH="${GRPO_SELF_IMITATION_WARMUP_START_EPOCH:-0}"
export GRPO_SELF_IMITATION_WARMUP_EPOCHS="${GRPO_SELF_IMITATION_WARMUP_EPOCHS:-2}"
export GRPO_SELF_IMITATION_TOP_K="${GRPO_SELF_IMITATION_TOP_K:-1}"
export GRPO_SELF_IMITATION_MIN_REWARD="${GRPO_SELF_IMITATION_MIN_REWARD:-0.88}"
export GRPO_SELF_IMITATION_MIN_REWARD_MARGIN="${GRPO_SELF_IMITATION_MIN_REWARD_MARGIN:-0.01}"
export GRPO_SELF_IMITATION_MAX_TARGET_SCENE_RATIO="${GRPO_SELF_IMITATION_MAX_TARGET_SCENE_RATIO:-0.5}"
export GRPO_SELF_IMITATION_BATCH_CAP_SCORE="${GRPO_SELF_IMITATION_BATCH_CAP_SCORE:-reward}"
export GRPO_SELF_IMITATION_BASELINE_MODE="${GRPO_SELF_IMITATION_BASELINE_MODE:-buffer_or_group_mean}"
export GRPO_SELF_IMITATION_TIMESTEP_SAMPLING="${GRPO_SELF_IMITATION_TIMESTEP_SAMPLING:-low_noise}"
export GRPO_SELF_IMITATION_REQUIRE_NC="${GRPO_SELF_IMITATION_REQUIRE_NC:-true}"
export GRPO_SELF_IMITATION_REQUIRE_DAC="${GRPO_SELF_IMITATION_REQUIRE_DAC:-true}"
export GRPO_SELF_IMITATION_REQUIRE_TTC="${GRPO_SELF_IMITATION_REQUIRE_TTC:-true}"
export GRPO_SELF_IMITATION_REQUIRE_DDC="${GRPO_SELF_IMITATION_REQUIRE_DDC:-true}"
export GRPO_SELF_IMITATION_NC_MIN_ABSOLUTE="${GRPO_SELF_IMITATION_NC_MIN_ABSOLUTE:-1.0}"
export GRPO_SELF_IMITATION_DAC_MIN_ABSOLUTE="${GRPO_SELF_IMITATION_DAC_MIN_ABSOLUTE:-1.0}"
export GRPO_SELF_IMITATION_TTC_MIN_ABSOLUTE="${GRPO_SELF_IMITATION_TTC_MIN_ABSOLUTE:-0.95}"
export GRPO_SELF_IMITATION_DDC_MIN_ABSOLUTE="${GRPO_SELF_IMITATION_DDC_MIN_ABSOLUTE:-0.99}"

export TRAIN_WAIT_FOR_FREE_GPUS="${TRAIN_WAIT_FOR_FREE_GPUS:-1}"
export TRAIN_GPU_MAX_MEM_USED_MB="${TRAIN_GPU_MAX_MEM_USED_MB:-2000}"
export TRAIN_GPU_MAX_UTIL="${TRAIN_GPU_MAX_UTIL:-5}"
export TRAIN_GPU_WAIT_POLL_SECONDS="${TRAIN_GPU_WAIT_POLL_SECONDS:-120}"
export START_EARLY_GATE_WATCHER="${START_EARLY_GATE_WATCHER:-1}"
export EARLY_GATE_THRESHOLD="${EARLY_GATE_THRESHOLD:-0.88}"
export EARLY_GATE_MARGIN="${EARLY_GATE_MARGIN:-0.005}"
export EARLY_GATE_STOP_ON_FAIL="${EARLY_GATE_STOP_ON_FAIL:-0}"
export EARLY_GATE_MIN_STOP_STEP="${EARLY_GATE_MIN_STOP_STEP:-3000}"

export RUN_TRAIN="${RUN_TRAIN:-1}"
export LAUNCH_EVAL_WATCHERS="${LAUNCH_EVAL_WATCHERS:-1}"
export PRIMARY_EVAL_HOST="${PRIMARY_EVAL_HOST:-training-vla-zt2}"
export SECONDARY_EVAL_HOST="${SECONDARY_EVAL_HOST:-}"
export EVAL_WAIT_FOR_FREE_GPUS="${EVAL_WAIT_FOR_FREE_GPUS:-1}"
export EVAL_GPU_MAX_MEM_USED_MB="${EVAL_GPU_MAX_MEM_USED_MB:-65000}"
export EVAL_GPU_MAX_UTIL="${EVAL_GPU_MAX_UTIL:-101}"

if [[ ! -d "${ELITE_BUFFER_DIR}" ]]; then
  echo "Elite buffer directory is required for offline GRPO self-imitation config: ${ELITE_BUFFER_DIR}" >&2
  exit 2
fi

exec "${REPO_ROOT}/scripts/training/launch_recogdrive_stage3_grpo_gspo_2b_local_stable.sh"
