#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-/mnt/project/VLA-AD}"

export RUN_NAME="${RUN_NAME:-stage3_grpo_rloo_selfimit_s16_lr1e4_b2acc4_$(date -u +%Y%m%dT%H%M%SZ)}"
export OUT_ROOT="${OUT_ROOT:-${ARTIFACT_ROOT}/outputs/${RUN_NAME}}"

# Preserve the original-GRPO training recipe. The only algorithmic addition is a
# small low-noise diffusion self-imitation loss on safe, high-reward on-policy
# samples whose reward is above a leave-one-out same-token baseline.
export RUN_TRAIN="${RUN_TRAIN:-0}"
export LAUNCH_EVAL_WATCHERS="${LAUNCH_EVAL_WATCHERS:-1}"
export CACHE_MODE="${CACHE_MODE:-online}"
export KILL_GPU_STRESS="${KILL_GPU_STRESS:-0}"
export LR="${LR:-1e-4}"
export MAX_EPOCHS="${MAX_EPOCHS:-20}"
export BATCH_SIZE="${BATCH_SIZE:-2}"
export ACCUMULATE_GRAD_BATCHES="${ACCUMULATE_GRAD_BATCHES:-4}"
export CHECKPOINT_EVERY_N_TRAIN_STEPS="${CHECKPOINT_EVERY_N_TRAIN_STEPS:-300}"
export GRPO_SAMPLE_TIME="${GRPO_SAMPLE_TIME:-16}"
export BC_ANNEAL="${BC_ANNEAL:-true}"
export BC_COEFF_START="${BC_COEFF_START:-0.10}"
export BC_COEFF_END="${BC_COEFF_END:-0.05}"
export BC_ANNEAL_EPOCHS="${BC_ANNEAL_EPOCHS:-5}"
export REFERENCE_KL_COEFF="${REFERENCE_KL_COEFF:-0.02}"
export REFERENCE_KL_CHUNK_SIZE="${REFERENCE_KL_CHUNK_SIZE:-16}"
export GRPO_USE_GSPO_RATIO="${GRPO_USE_GSPO_RATIO:-true}"
export GRPO_GSPO_CLIP_LOW="${GRPO_GSPO_CLIP_LOW:-0.05}"
export GRPO_GSPO_CLIP_HIGH="${GRPO_GSPO_CLIP_HIGH:-0.05}"
export GRPO_BEHAVIOR_POLICY_SYNC_INTERVAL="${GRPO_BEHAVIOR_POLICY_SYNC_INTERVAL:-4}"
export GRPO_BEHAVIOR_POLICY_SAMPLE="${GRPO_BEHAVIOR_POLICY_SAMPLE:-true}"
export GRPO_NORMALIZE_ADVANTAGE_BATCH="${GRPO_NORMALIZE_ADVANTAGE_BATCH:-false}"
export GRPO_ADVANTAGE_CLIP_ABS="${GRPO_ADVANTAGE_CLIP_ABS:-0.0}"
export GRPO_SCHEDULER_EPOCHS="${GRPO_SCHEDULER_EPOCHS:-20}"
export GRPO_SCHEDULER_WARMUP_EPOCHS="${GRPO_SCHEDULER_WARMUP_EPOCHS:-0}"
export GRPO_SCHEDULER_MIN_LR="${GRPO_SCHEDULER_MIN_LR:-1e-5}"

export OFFLINE_RL_ENABLED="${OFFLINE_RL_ENABLED:-true}"
export ELITE_BUFFER_DIR="${ELITE_BUFFER_DIR:-${ARTIFACT_ROOT}/cache/recogdrive_stage3_awac_elite_buffer_train_v2_stage3_awac_iql_dualhost_20260612T182947Z}"
export OFFLINE_RL_CACHE_ELITE_RECORDS_IN_MEMORY="${OFFLINE_RL_CACHE_ELITE_RECORDS_IN_MEMORY:-false}"
export OFFLINE_RL_STRICT_REWARD_SUBMETRICS="${OFFLINE_RL_STRICT_REWARD_SUBMETRICS:-true}"
export OFFLINE_RL_MISSING_SUBMETRIC_POLICY="${OFFLINE_RL_MISSING_SUBMETRIC_POLICY:-error}"
export OFFLINE_RL_USE_BATCHED_PDM_SCORING="${OFFLINE_RL_USE_BATCHED_PDM_SCORING:-true}"
export OFFLINE_RL_USE_EXACT_ARRAY_PDM_STATE_CONVERSION="${OFFLINE_RL_USE_EXACT_ARRAY_PDM_STATE_CONVERSION:-true}"
export OFFLINE_RL_USE_FAST_PDM_SCORER="${OFFLINE_RL_USE_FAST_PDM_SCORER:-true}"
export OFFLINE_RL_PDM_SHADOW_CHECK="${OFFLINE_RL_PDM_SHADOW_CHECK:-false}"

export GRPO_BUFFER_GUIDANCE_ENABLED="${GRPO_BUFFER_GUIDANCE_ENABLED:-false}"
export GRPO_BUFFER_REWARD_BONUS_WEIGHT="${GRPO_BUFFER_REWARD_BONUS_WEIGHT:-0.0}"
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT="${GRPO_BUFFER_DISTILL_LOSS_WEIGHT:-0.0}"
export GRPO_BUFFER_DISTILL_MIN_REWARD_MARGIN="${GRPO_BUFFER_DISTILL_MIN_REWARD_MARGIN:-0.01}"
export GRPO_BUFFER_DISTILL_TIMESTEP_SAMPLING="${GRPO_BUFFER_DISTILL_TIMESTEP_SAMPLING:-low_noise}"

export GRPO_SELF_IMITATION_LOSS_WEIGHT="${GRPO_SELF_IMITATION_LOSS_WEIGHT:-0.01}"
export GRPO_SELF_IMITATION_LOSS_SCHEDULE="${GRPO_SELF_IMITATION_LOSS_SCHEDULE:-linear_warmup}"
export GRPO_SELF_IMITATION_LOSS_WEIGHT_START="${GRPO_SELF_IMITATION_LOSS_WEIGHT_START:-0.0}"
export GRPO_SELF_IMITATION_WARMUP_START_EPOCH="${GRPO_SELF_IMITATION_WARMUP_START_EPOCH:-0}"
export GRPO_SELF_IMITATION_WARMUP_EPOCHS="${GRPO_SELF_IMITATION_WARMUP_EPOCHS:-2}"
export GRPO_SELF_IMITATION_TOP_K="${GRPO_SELF_IMITATION_TOP_K:-1}"
export GRPO_SELF_IMITATION_MIN_REWARD="${GRPO_SELF_IMITATION_MIN_REWARD:-0.88}"
export GRPO_SELF_IMITATION_MIN_REWARD_MARGIN="${GRPO_SELF_IMITATION_MIN_REWARD_MARGIN:-0.01}"
export GRPO_SELF_IMITATION_MAX_TARGET_SCENE_RATIO="${GRPO_SELF_IMITATION_MAX_TARGET_SCENE_RATIO:-0.5}"
export GRPO_SELF_IMITATION_BATCH_CAP_SCORE="${GRPO_SELF_IMITATION_BATCH_CAP_SCORE:-reward}"
export GRPO_SELF_IMITATION_BASELINE_MODE="${GRPO_SELF_IMITATION_BASELINE_MODE:-group_leave_one_out}"
export GRPO_SELF_IMITATION_TIMESTEP_SAMPLING="${GRPO_SELF_IMITATION_TIMESTEP_SAMPLING:-low_noise}"

export TRAIN_WAIT_FOR_FREE_GPUS="${TRAIN_WAIT_FOR_FREE_GPUS:-1}"
export TRAIN_GPU_MAX_MEM_USED_MB="${TRAIN_GPU_MAX_MEM_USED_MB:-2000}"
export TRAIN_GPU_MAX_UTIL="${TRAIN_GPU_MAX_UTIL:-5}"
export TRAIN_GPU_WAIT_POLL_SECONDS="${TRAIN_GPU_WAIT_POLL_SECONDS:-120}"

if [[ ! -d "${ELITE_BUFFER_DIR}" ]]; then
  echo "Elite buffer directory is required by the shared Stage3 launcher sanity check: ${ELITE_BUFFER_DIR}" >&2
  exit 2
fi

exec bash "${REPO_ROOT}/scripts/training/launch_recogdrive_stage3_grpo_gspo_2b_local_stable.sh"
