#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

export PYTHON_BIN="${PYTHON_BIN:-/root/miniconda3/envs/navsim/bin/python}"
export ARTIFACT_ROOT="${ARTIFACT_ROOT:-/mnt/project/VLA-AD}"
export NAVSIM_DATA_ROOT="${NAVSIM_DATA_ROOT:-/mnt/navsim}"
export RUN_NAME="${RUN_NAME:-stage3_safe_diffgrpo_pp_base_elite142_twoexpert_s16_lr1e4_b2acc4_$(date -u +%Y%m%dT%H%M%SZ)}"
export OUT_ROOT="${OUT_ROOT:-${ARTIFACT_ROOT}/outputs/${RUN_NAME}}"

if [[ -z "${IL_CHECKPOINT:-}" ]]; then
  ELITE142_SNAPSHOT_CKPT="${ARTIFACT_ROOT}/outputs/two_expert_slot_stage2_prefuse_v2_dual_val6000_navtest_watch_20260617T020404Z/navtest_elite_full103k_top3/checkpoint_snapshots/epoch_142-step_115115.ckpt/epoch=142-step=115115.ckpt"
  ELITE142_TRAIN_CKPT="${ARTIFACT_ROOT}/outputs/two_expert_slot_stage2_prefuse_v2_elite_full103k_random_8gpu_minlr5e6_20260616T230916Z_jsonfix/stage2_train/lightning_logs/version_0/checkpoints/epoch=142-step=115115.ckpt"
  if [[ -f "${ELITE142_SNAPSHOT_CKPT}" ]]; then
    export IL_CHECKPOINT="${ELITE142_SNAPSHOT_CKPT}"
  elif [[ -f "${ELITE142_TRAIN_CKPT}" ]]; then
    export IL_CHECKPOINT="${ELITE142_TRAIN_CKPT}"
  else
    export IL_CHECKPOINT="${ELITE142_SNAPSHOT_CKPT}"
  fi
else
  export IL_CHECKPOINT
fi
export VLM_PATH="${VLM_PATH:-${ARTIFACT_ROOT}/checkpoints/recogdrive/ReCogDrive-VLM-2B}"
export METRIC_CACHE_DIR="${METRIC_CACHE_DIR:-${ARTIFACT_ROOT}/cache/metric_cache_train_full}"
export HIDDEN_CACHE_DIR="${HIDDEN_CACHE_DIR:-${ARTIFACT_ROOT}/cache/two_expert_slot/stage1_v2_20260615_174154/hidden_navtrain_stage1_v2_clean_bf16_20260616T164153Z}"

export CACHE_MODE="${CACHE_MODE:-offline}"
export KILL_GPU_STRESS="${KILL_GPU_STRESS:-0}"
export GPU_LIST="${GPU_LIST:-0,1,2,3,4,5,6,7}"
export GPUS_PER_NODE="${GPUS_PER_NODE:-8}"
export DDP_STRATEGY="${DDP_STRATEGY:-ddp}"
export CUDA_LAUNCH_BLOCKING="${CUDA_LAUNCH_BLOCKING:-0}"

export LR="${LR:-1e-4}"
export STAGE3_OBJECTIVE="${STAGE3_OBJECTIVE:-none}"
export DIT_DROPOUT="${DIT_DROPOUT:-0.05}"
export MAX_EPOCHS="${MAX_EPOCHS:-20}"
export BATCH_SIZE="${BATCH_SIZE:-2}"
export ACCUMULATE_GRAD_BATCHES="${ACCUMULATE_GRAD_BATCHES:-4}"
export GRPO_SAMPLE_TIME="${GRPO_SAMPLE_TIME:-16}"

# ReCogDrive-91 / Reinforce++ diffusion-RL stability recipe.
export GRPO_ADVANTAGE_MODE="${GRPO_ADVANTAGE_MODE:-safe_rpp}"
export GRPO_NORMALIZE_ADVANTAGE_BATCH="${GRPO_NORMALIZE_ADVANTAGE_BATCH:-false}"
export GRPO_ADVANTAGE_CLIP_ABS="${GRPO_ADVANTAGE_CLIP_ABS:-5.0}"
export GRPO_DENOISED_CLIP_VALUE="${GRPO_DENOISED_CLIP_VALUE:-1.0}"
export GRPO_EVAL_RANDN_CLIP_VALUE="${GRPO_EVAL_RANDN_CLIP_VALUE:-1.0}"
export GRPO_RANDN_CLIP_VALUE="${GRPO_RANDN_CLIP_VALUE:-5.0}"
export GRPO_FINAL_ACTION_CLIP_VALUE="${GRPO_FINAL_ACTION_CLIP_VALUE:-1.0}"
export GRPO_EVAL_MIN_SAMPLING_DENOISING_STD="${GRPO_EVAL_MIN_SAMPLING_DENOISING_STD:-0.0001}"
export GRPO_MIN_SAMPLING_DENOISING_STD="${GRPO_MIN_SAMPLING_DENOISING_STD:-0.04}"
export GRPO_MIN_LOGPROB_DENOISING_STD="${GRPO_MIN_LOGPROB_DENOISING_STD:-0.1}"
export GRPO_CLIP_ADVANTAGE_LOWER_QUANTILE="${GRPO_CLIP_ADVANTAGE_LOWER_QUANTILE:-0.0}"
export GRPO_CLIP_ADVANTAGE_UPPER_QUANTILE="${GRPO_CLIP_ADVANTAGE_UPPER_QUANTILE:-1.0}"
export GRPO_GAMMA_DENOISING="${GRPO_GAMMA_DENOISING:-0.6}"

export BC_ANNEAL="${BC_ANNEAL:-true}"
export BC_COEFF_START="${BC_COEFF_START:-0.10}"
export BC_COEFF_END="${BC_COEFF_END:-0.05}"
export BC_ANNEAL_EPOCHS="${BC_ANNEAL_EPOCHS:-5}"
export REFERENCE_KL_COEFF="${REFERENCE_KL_COEFF:-0.02}"
export REFERENCE_KL_CHUNK_SIZE="${REFERENCE_KL_CHUNK_SIZE:-16}"

# Base++ keeps on-policy Safe DiffGRPO primary: no GSPO, no hard gate, no buffer.
export GRPO_USE_GSPO_RATIO="${GRPO_USE_GSPO_RATIO:-false}"
export GRPO_HARD_GATE_TTC="${GRPO_HARD_GATE_TTC:-false}"
export GRPO_HARD_GATE_DDC="${GRPO_HARD_GATE_DDC:-false}"
export GRPO_REWARD_MODE="${GRPO_REWARD_MODE:-safe_diffgrpo}"
export GRPO_SAFETY_ADVANTAGE_MODE="${GRPO_SAFETY_ADVANTAGE_MODE:-soft_penalty}"
export GRPO_TTC_SAFE_THRESHOLD="${GRPO_TTC_SAFE_THRESHOLD:-0.95}"
export GRPO_DDC_SAFE_THRESHOLD="${GRPO_DDC_SAFE_THRESHOLD:-0.99}"
export GRPO_SOFT_SAFETY_PENALTY_WEIGHT="${GRPO_SOFT_SAFETY_PENALTY_WEIGHT:-0.50}"
export GRPO_SOFT_SAFETY_PENALTY_CLIP="${GRPO_SOFT_SAFETY_PENALTY_CLIP:-0.50}"
export GRPO_SOFT_SAFETY_MIN_REWARD="${GRPO_SOFT_SAFETY_MIN_REWARD:-0.0}"

export OFFLINE_RL_ENABLED="${OFFLINE_RL_ENABLED:-false}"
export GRPO_BUFFER_GUIDANCE_ENABLED="${GRPO_BUFFER_GUIDANCE_ENABLED:-false}"
export GRPO_BUFFER_REWARD_BONUS_WEIGHT="${GRPO_BUFFER_REWARD_BONUS_WEIGHT:-0.0}"
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT="${GRPO_BUFFER_DISTILL_LOSS_WEIGHT:-0.0}"
export GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT="${GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT:-0.0}"
export GRPO_SELF_IMITATION_LOSS_WEIGHT="${GRPO_SELF_IMITATION_LOSS_WEIGHT:-0.0}"

# Match the elite stage2 prefuse/two-expert architecture.
export USE_TWO_EXPERT_SLOTS="${USE_TWO_EXPERT_SLOTS:-true}"
export TWO_EXPERT_CACHE_MODE="${TWO_EXPERT_CACHE_MODE:-true}"
export TWO_EXPERT_SLOT_MODE="${TWO_EXPERT_SLOT_MODE:-vlm_soft_slots}"
export TWO_EXPERT_CONDITION_MODE="${TWO_EXPERT_CONDITION_MODE:-prefuse_cross_attention}"
export TWO_EXPERT_DIT_CONDITION_MODE="${TWO_EXPERT_DIT_CONDITION_MODE:-prefuse_cross_attention}"
export TWO_EXPERT_PLANNER_DIM="${TWO_EXPERT_PLANNER_DIM:-384}"
export TWO_EXPERT_USE_RAW_VLM_BASE="${TWO_EXPERT_USE_RAW_VLM_BASE:-true}"
export TWO_EXPERT_ZERO_INIT_DELTAS="${TWO_EXPERT_ZERO_INIT_DELTAS:-true}"
export TWO_EXPERT_NUM_DYN_GROUPS="${TWO_EXPERT_NUM_DYN_GROUPS:-3}"
export TWO_EXPERT_DYN_TOKENS_PER_GROUP="${TWO_EXPERT_DYN_TOKENS_PER_GROUP:-12}"
export TWO_EXPERT_NUM_GEO_TOKENS="${TWO_EXPERT_NUM_GEO_TOKENS:-12}"
export TWO_EXPERT_MEMORY_TOKENS_TO_DIT="${TWO_EXPERT_MEMORY_TOKENS_TO_DIT:-false}"
export TWO_EXPERT_MEMORY_SCALE_INIT="${TWO_EXPERT_MEMORY_SCALE_INIT:-1.0}"
export TWO_EXPERT_PREFUSION_HEADS="${TWO_EXPERT_PREFUSION_HEADS:-8}"
export TWO_EXPERT_PREFUSION_DROPOUT="${TWO_EXPERT_PREFUSION_DROPOUT:-0.10}"
export TWO_EXPERT_PREFUSION_TOKEN_DROPOUT="${TWO_EXPERT_PREFUSION_TOKEN_DROPOUT:-0.05}"
export TWO_EXPERT_PREFUSION_CONDITION_DROPOUT="${TWO_EXPERT_PREFUSION_CONDITION_DROPOUT:-0.10}"
export TWO_EXPERT_PREFUSION_SCALE_INIT="${TWO_EXPERT_PREFUSION_SCALE_INIT:-1.0}"
export TWO_EXPERT_PREFUSION_ZERO_INIT="${TWO_EXPERT_PREFUSION_ZERO_INIT:-true}"

export GRPO_SCHEDULER_EPOCHS="${GRPO_SCHEDULER_EPOCHS:-${MAX_EPOCHS}}"
export GRPO_SCHEDULER_WARMUP_EPOCHS="${GRPO_SCHEDULER_WARMUP_EPOCHS:-0}"
export GRPO_SCHEDULER_MIN_LR="${GRPO_SCHEDULER_MIN_LR:-1e-5}"
export CHECKPOINT_EVERY_N_EPOCHS="${CHECKPOINT_EVERY_N_EPOCHS:-1}"
export CHECKPOINT_EVERY_N_TRAIN_STEPS="${CHECKPOINT_EVERY_N_TRAIN_STEPS:-300}"

export START_EARLY_GATE_WATCHER="${START_EARLY_GATE_WATCHER:-1}"
export EARLY_GATE_THRESHOLD="${EARLY_GATE_THRESHOLD:-0.88}"
export EARLY_GATE_MARGIN="${EARLY_GATE_MARGIN:-0.005}"
export EARLY_GATE_STOP_ON_FAIL="${EARLY_GATE_STOP_ON_FAIL:-0}"
export EARLY_GATE_MIN_STOP_STEP="${EARLY_GATE_MIN_STOP_STEP:-3000}"

if [[ "${USE_STABLE_LAUNCHER:-1}" == "1" ]]; then
  exec "${REPO_ROOT}/scripts/training/launch_recogdrive_stage3_rl_2b_local_stable.sh"
fi

exec "${REPO_ROOT}/scripts/training/run_recogdrive_stage3_rl_2b_local.sh"
