#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-/mnt/project/VLA-AD}"

export RUN_NAME="${RUN_NAME:-stage3_grpo_buffer_dpo_mainhardgate_step300_s16_lr1e4_b2acc4_8gpu_$(date -u +%Y%m%dT%H%M%SZ)}"
export OUT_ROOT="${OUT_ROOT:-${ARTIFACT_ROOT}/outputs/${RUN_NAME}}"

# Keep this launcher explicit: it should be started after the active v3 step300
# gate is known, not accidentally during import/smoke checks.
export RUN_TRAIN="${RUN_TRAIN:-0}"
export LAUNCH_EVAL_WATCHERS="${LAUNCH_EVAL_WATCHERS:-0}"

export LR="${LR:-1e-4}"
export MAX_EPOCHS="${MAX_EPOCHS:-20}"
export BATCH_SIZE="${BATCH_SIZE:-2}"
export ACCUMULATE_GRAD_BATCHES="${ACCUMULATE_GRAD_BATCHES:-4}"
export GRPO_SAMPLE_TIME="${GRPO_SAMPLE_TIME:-16}"
export BC_ANNEAL="${BC_ANNEAL:-true}"
export BC_COEFF_START="${BC_COEFF_START:-0.10}"
export BC_COEFF_END="${BC_COEFF_END:-0.05}"
export BC_ANNEAL_EPOCHS="${BC_ANNEAL_EPOCHS:-5}"
export REFERENCE_KL_COEFF="${REFERENCE_KL_COEFF:-0.02}"
export REFERENCE_KL_CHUNK_SIZE="${REFERENCE_KL_CHUNK_SIZE:-0}"

export GRPO_USE_GSPO_RATIO="${GRPO_USE_GSPO_RATIO:-true}"
export GRPO_GSPO_CLIP_LOW="${GRPO_GSPO_CLIP_LOW:-0.05}"
export GRPO_GSPO_CLIP_HIGH="${GRPO_GSPO_CLIP_HIGH:-0.05}"
export GRPO_BEHAVIOR_POLICY_SYNC_INTERVAL="${GRPO_BEHAVIOR_POLICY_SYNC_INTERVAL:-4}"
export GRPO_BEHAVIOR_POLICY_SAMPLE="${GRPO_BEHAVIOR_POLICY_SAMPLE:-true}"
export GRPO_HARD_GATE_TTC="${GRPO_HARD_GATE_TTC:-true}"
export GRPO_HARD_GATE_DDC="${GRPO_HARD_GATE_DDC:-true}"
export GRPO_TTC_SAFE_THRESHOLD="${GRPO_TTC_SAFE_THRESHOLD:-0.95}"
export GRPO_DDC_SAFE_THRESHOLD="${GRPO_DDC_SAFE_THRESHOLD:-0.99}"

export CHECKPOINT_EVERY_N_EPOCHS="${CHECKPOINT_EVERY_N_EPOCHS:-1}"
export CHECKPOINT_EVERY_N_TRAIN_STEPS="${CHECKPOINT_EVERY_N_TRAIN_STEPS:-300}"
export START_EARLY_GATE_WATCHER="${START_EARLY_GATE_WATCHER:-1}"
export EARLY_GATE_THRESHOLD="${EARLY_GATE_THRESHOLD:-0.88}"
export EARLY_GATE_MARGIN="${EARLY_GATE_MARGIN:-0.005}"
export EARLY_GATE_STOP_ON_FAIL="${EARLY_GATE_STOP_ON_FAIL:-0}"

export OFFLINE_RL_ENABLED="${OFFLINE_RL_ENABLED:-true}"
export ELITE_BUFFER_DIR="${ELITE_BUFFER_DIR:-${ARTIFACT_ROOT}/cache/recogdrive_stage3_awac_elite_buffer_train_v2_stage3_awac_iql_dualhost_20260612T182947Z}"
export OFFLINE_RL_CACHE_ELITE_RECORDS_IN_MEMORY="${OFFLINE_RL_CACHE_ELITE_RECORDS_IN_MEMORY:-false}"
export GRPO_BUFFER_GUIDANCE_ENABLED="${GRPO_BUFFER_GUIDANCE_ENABLED:-true}"
export GRPO_BUFFER_REWARD_BONUS_WEIGHT="${GRPO_BUFFER_REWARD_BONUS_WEIGHT:-0.0}"
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT="${GRPO_BUFFER_DISTILL_LOSS_WEIGHT:-0.0}"
export GRPO_BUFFER_DISTILL_TOP_K="${GRPO_BUFFER_DISTILL_TOP_K:-1}"
export GRPO_BUFFER_DISTILL_MIN_REWARD_MARGIN="${GRPO_BUFFER_DISTILL_MIN_REWARD_MARGIN:-0.0}"

export GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT="${GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT:-0.02}"
export GRPO_BUFFER_PREFERENCE_DPO_LOSS_SCHEDULE="${GRPO_BUFFER_PREFERENCE_DPO_LOSS_SCHEDULE:-linear_warmup}"
export GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT_START="${GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT_START:-0.0}"
export GRPO_BUFFER_PREFERENCE_DPO_WARMUP_START_EPOCH="${GRPO_BUFFER_PREFERENCE_DPO_WARMUP_START_EPOCH:-0}"
export GRPO_BUFFER_PREFERENCE_DPO_WARMUP_EPOCHS="${GRPO_BUFFER_PREFERENCE_DPO_WARMUP_EPOCHS:-2}"
export GRPO_BUFFER_PREFERENCE_DPO_TIMESTEP_SAMPLING="${GRPO_BUFFER_PREFERENCE_DPO_TIMESTEP_SAMPLING:-uniform}"
export GRPO_BUFFER_PREFERENCE_DPO_BETA="${GRPO_BUFFER_PREFERENCE_DPO_BETA:-8.0}"
export GRPO_BUFFER_PREFERENCE_DPO_PAIR_MODE="${GRPO_BUFFER_PREFERENCE_DPO_PAIR_MODE:-best_vs_gt_il}"
export GRPO_BUFFER_PREFERENCE_DPO_MIN_REWARD_GAP="${GRPO_BUFFER_PREFERENCE_DPO_MIN_REWARD_GAP:-0.02}"
export GRPO_BUFFER_PREFERENCE_DPO_MAX_PAIRS_PER_SCENE="${GRPO_BUFFER_PREFERENCE_DPO_MAX_PAIRS_PER_SCENE:-2}"
export GRPO_BUFFER_PREFERENCE_DPO_INCLUDE_IL="${GRPO_BUFFER_PREFERENCE_DPO_INCLUDE_IL:-true}"

# Default to isolating buffer-DPO. Set this to 0.01 to test v3 + buffer-DPO
# after the v3 gate confirms self-imitation is safe enough to keep.
export GRPO_SELF_IMITATION_LOSS_WEIGHT="${GRPO_SELF_IMITATION_LOSS_WEIGHT:-0.0}"
export GRPO_SELF_IMITATION_MAX_TARGET_SCENE_RATIO="${GRPO_SELF_IMITATION_MAX_TARGET_SCENE_RATIO:-0.5}"
export GRPO_SELF_IMITATION_BASELINE_MODE="${GRPO_SELF_IMITATION_BASELINE_MODE:-group_leave_one_out}"
export GRPO_SELF_IMITATION_REQUIRE_NC="${GRPO_SELF_IMITATION_REQUIRE_NC:-true}"
export GRPO_SELF_IMITATION_REQUIRE_DAC="${GRPO_SELF_IMITATION_REQUIRE_DAC:-true}"
export GRPO_SELF_IMITATION_REQUIRE_TTC="${GRPO_SELF_IMITATION_REQUIRE_TTC:-true}"
export GRPO_SELF_IMITATION_REQUIRE_DDC="${GRPO_SELF_IMITATION_REQUIRE_DDC:-true}"
export GRPO_SELF_IMITATION_TTC_MIN_ABSOLUTE="${GRPO_SELF_IMITATION_TTC_MIN_ABSOLUTE:-0.95}"
export GRPO_SELF_IMITATION_DDC_MIN_ABSOLUTE="${GRPO_SELF_IMITATION_DDC_MIN_ABSOLUTE:-0.99}"

export TRAIN_WAIT_FOR_FREE_GPUS="${TRAIN_WAIT_FOR_FREE_GPUS:-1}"
export TRAIN_GPU_MAX_MEM_USED_MB="${TRAIN_GPU_MAX_MEM_USED_MB:-2000}"
export TRAIN_GPU_MAX_UTIL="${TRAIN_GPU_MAX_UTIL:-5}"
export TRAIN_GPU_WAIT_POLL_SECONDS="${TRAIN_GPU_WAIT_POLL_SECONDS:-120}"

exec bash "${REPO_ROOT}/scripts/training/launch_recogdrive_stage3_grpo_gspo_2b_local_stable.sh"
