#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Evidence basis:
# - The 2026-06-15 soft-safety + buffer-distill run was strongest at matched
#   step600, but underperformed the matched epoch0 control mainly through EP/DAC.
# - Keep GRPO/GSPO + reference KL as the main policy-improvement path.
# - Use train-only buffer/self-imitation only as an early stabilizing teacher,
#   then decay auxiliary diffusion regression before the epoch0 comparison.

export RUN_NAME="${RUN_NAME:-stage3_grpo_softsafety_auxdecay_s16_lr1e4_b2acc4_20e_$(date -u +%Y%m%dT%H%M%SZ)}"

export LR="${LR:-1e-4}"
export MAX_EPOCHS="${MAX_EPOCHS:-20}"
export GRPO_SCHEDULER_EPOCHS="${GRPO_SCHEDULER_EPOCHS:-${MAX_EPOCHS}}"
export GRPO_SCHEDULER_MIN_LR="${GRPO_SCHEDULER_MIN_LR:-1e-5}"
export GRPO_SAMPLE_TIME="${GRPO_SAMPLE_TIME:-16}"
export BATCH_SIZE="${BATCH_SIZE:-2}"
export ACCUMULATE_GRAD_BATCHES="${ACCUMULATE_GRAD_BATCHES:-4}"

export GRPO_SAFETY_ADVANTAGE_MODE="${GRPO_SAFETY_ADVANTAGE_MODE:-soft_penalty}"
export GRPO_TTC_SAFE_THRESHOLD="${GRPO_TTC_SAFE_THRESHOLD:-0.95}"
export GRPO_DDC_SAFE_THRESHOLD="${GRPO_DDC_SAFE_THRESHOLD:-0.99}"
export GRPO_SOFT_SAFETY_PENALTY_WEIGHT="${GRPO_SOFT_SAFETY_PENALTY_WEIGHT:-0.50}"
export GRPO_SOFT_SAFETY_PENALTY_CLIP="${GRPO_SOFT_SAFETY_PENALTY_CLIP:-0.50}"
export GRPO_SOFT_SAFETY_MIN_REWARD="${GRPO_SOFT_SAFETY_MIN_REWARD:-0.0}"

export GRPO_BUFFER_GUIDANCE_ENABLED="${GRPO_BUFFER_GUIDANCE_ENABLED:-true}"
export GRPO_BUFFER_REWARD_BONUS_WEIGHT="${GRPO_BUFFER_REWARD_BONUS_WEIGHT:-0.0}"
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT="${GRPO_BUFFER_DISTILL_LOSS_WEIGHT:-0.01}"
export GRPO_BUFFER_DISTILL_LOSS_SCHEDULE="${GRPO_BUFFER_DISTILL_LOSS_SCHEDULE:-linear_warmup_cosine_decay}"
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT_START="${GRPO_BUFFER_DISTILL_LOSS_WEIGHT_START:-0.0}"
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT_END="${GRPO_BUFFER_DISTILL_LOSS_WEIGHT_END:-0.0}"
export GRPO_BUFFER_DISTILL_WARMUP_START_EPOCH="${GRPO_BUFFER_DISTILL_WARMUP_START_EPOCH:-0}"
export GRPO_BUFFER_DISTILL_WARMUP_EPOCHS="${GRPO_BUFFER_DISTILL_WARMUP_EPOCHS:-4}"
export GRPO_BUFFER_DISTILL_DECAY_START_STEP="${GRPO_BUFFER_DISTILL_DECAY_START_STEP:-600}"
export GRPO_BUFFER_DISTILL_DECAY_END_STEP="${GRPO_BUFFER_DISTILL_DECAY_END_STEP:-1330}"
export GRPO_BUFFER_DISTILL_TOP_K="${GRPO_BUFFER_DISTILL_TOP_K:-1}"
export GRPO_BUFFER_DISTILL_MIN_REWARD_MARGIN="${GRPO_BUFFER_DISTILL_MIN_REWARD_MARGIN:-0.02}"
export GRPO_BUFFER_DISTILL_TIMESTEP_SAMPLING="${GRPO_BUFFER_DISTILL_TIMESTEP_SAMPLING:-low_noise}"

export GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT="${GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT:-0.0}"

export GRPO_SELF_IMITATION_LOSS_WEIGHT="${GRPO_SELF_IMITATION_LOSS_WEIGHT:-0.01}"
export GRPO_SELF_IMITATION_LOSS_SCHEDULE="${GRPO_SELF_IMITATION_LOSS_SCHEDULE:-linear_warmup_cosine_decay}"
export GRPO_SELF_IMITATION_LOSS_WEIGHT_START="${GRPO_SELF_IMITATION_LOSS_WEIGHT_START:-0.0}"
export GRPO_SELF_IMITATION_LOSS_WEIGHT_END="${GRPO_SELF_IMITATION_LOSS_WEIGHT_END:-0.0}"
export GRPO_SELF_IMITATION_WARMUP_START_EPOCH="${GRPO_SELF_IMITATION_WARMUP_START_EPOCH:-0}"
export GRPO_SELF_IMITATION_WARMUP_EPOCHS="${GRPO_SELF_IMITATION_WARMUP_EPOCHS:-2}"
export GRPO_SELF_IMITATION_DECAY_START_STEP="${GRPO_SELF_IMITATION_DECAY_START_STEP:-600}"
export GRPO_SELF_IMITATION_DECAY_END_STEP="${GRPO_SELF_IMITATION_DECAY_END_STEP:-1330}"
export GRPO_SELF_IMITATION_TOP_K="${GRPO_SELF_IMITATION_TOP_K:-1}"
export GRPO_SELF_IMITATION_MIN_REWARD="${GRPO_SELF_IMITATION_MIN_REWARD:-0.88}"
export GRPO_SELF_IMITATION_MIN_REWARD_MARGIN="${GRPO_SELF_IMITATION_MIN_REWARD_MARGIN:-0.01}"
export GRPO_SELF_IMITATION_MAX_TARGET_SCENE_RATIO="${GRPO_SELF_IMITATION_MAX_TARGET_SCENE_RATIO:-0.5}"
export GRPO_SELF_IMITATION_BATCH_CAP_SCORE="${GRPO_SELF_IMITATION_BATCH_CAP_SCORE:-reward}"
export GRPO_SELF_IMITATION_BASELINE_MODE="${GRPO_SELF_IMITATION_BASELINE_MODE:-buffer_or_group_mean}"
export GRPO_SELF_IMITATION_TIMESTEP_SAMPLING="${GRPO_SELF_IMITATION_TIMESTEP_SAMPLING:-low_noise}"
export GRPO_SELF_IMITATION_REQUIRE_NC="${GRPO_SELF_IMITATION_REQUIRE_NC:-true}"
export GRPO_SELF_IMITATION_REQUIRE_DAC="${GRPO_SELF_IMITATION_REQUIRE_DAC:-true}"
export GRPO_SELF_IMITATION_REQUIRE_TTC="${GRPO_SELF_IMITATION_REQUIRE_TTC:-true}"
export GRPO_SELF_IMITATION_REQUIRE_DDC="${GRPO_SELF_IMITATION_REQUIRE_DDC:-true}"
export GRPO_SELF_IMITATION_NC_MIN_ABSOLUTE="${GRPO_SELF_IMITATION_NC_MIN_ABSOLUTE:-1.0}"
export GRPO_SELF_IMITATION_DAC_MIN_ABSOLUTE="${GRPO_SELF_IMITATION_DAC_MIN_ABSOLUTE:-1.0}"
export GRPO_SELF_IMITATION_TTC_MIN_ABSOLUTE="${GRPO_SELF_IMITATION_TTC_MIN_ABSOLUTE:-0.95}"
export GRPO_SELF_IMITATION_DDC_MIN_ABSOLUTE="${GRPO_SELF_IMITATION_DDC_MIN_ABSOLUTE:-0.99}"
export EARLY_GATE_MIN_STOP_STEP="${EARLY_GATE_MIN_STOP_STEP:-3000}"

exec "${REPO_ROOT}/scripts/training/launch_recogdrive_stage3_grpo_softsafety_selfimit_2b_local.sh"
