#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

SUPPORT_ARCHIVE_PATH="${SUPPORT_ARCHIVE_PATH:?set SUPPORT_ARCHIVE_PATH}"

export ELITE_BUFFER_DIR="${SUPPORT_ARCHIVE_PATH}"
export SUPPORT_ARCHIVE_PATH="${SUPPORT_ARCHIVE_PATH}"
export HIDDEN_CACHE_DIR="${HIDDEN_CACHE_DIR:-/mnt/project/VLA-AD/cache/recogdrive_official_stage1_hidden_navtrain_2b}"
export ONLINE_AWAC_CANDIDATES=false
export STAGE3_OBJECTIVE="${STAGE3_OBJECTIVE:-dpsi}"
export VALIDATE_ELITE_BUFFER="${VALIDATE_ELITE_BUFFER:-false}"
export SG_FPS_USE_DPSI=true
export SG_FPS_DPSI_TOP_M="${SG_FPS_DPSI_TOP_M:-12}"
export USE_FS_NORM="${USE_FS_NORM:-false}"
export FS_NORM_STATS_PATH="${FS_NORM_STATS_PATH:-}"
export USE_PLANNING_TOKEN_ADAPTER="${USE_PLANNING_TOKEN_ADAPTER:-false}"
export PLANNING_NUM_TOKENS="${PLANNING_NUM_TOKENS:-16}"
export PLANNING_NUM_HEADS="${PLANNING_NUM_HEADS:-8}"
export PLANNING_CONDITION_LAYERS="${PLANNING_CONDITION_LAYERS:-cross_attention}"
export PLANNING_GATE_INIT="${PLANNING_GATE_INIT:-0.05}"
export PLANNING_CONTEXT_GATE_INIT="${PLANNING_CONTEXT_GATE_INIT:-0.05}"
export PLANNING_CONDITION_DROPOUT="${PLANNING_CONDITION_DROPOUT:-0.10}"
export X0_AUX_WEIGHT="${X0_AUX_WEIGHT:-0.0}"
export DELTA_AUX_WEIGHT="${DELTA_AUX_WEIGHT:-0.0}"
export GEO_AUX_WEIGHT="${GEO_AUX_WEIGHT:-0.0}"
export TRAJECTORY_AUX_WEIGHT="${TRAJECTORY_AUX_WEIGHT:-0.0}"
export FEASIBILITY_AUX_WEIGHT="${FEASIBILITY_AUX_WEIGHT:-0.0}"
export AUX_ALPHA_POWER="${AUX_ALPHA_POWER:-1.0}"
export AUX_WARMUP_EPOCHS="${AUX_WARMUP_EPOCHS:-10}"
export TANGENT_MARGIN_RAD="${TANGENT_MARGIN_RAD:-0.08}"
export CURVATURE_MARGIN="${CURVATURE_MARGIN:-0.05}"
export MIN_SEGMENT_LENGTH="${MIN_SEGMENT_LENGTH:-0.20}"
export RUN_STAGE3="${RUN_STAGE3:-1}"
export DRY_RUN="${DRY_RUN:-0}"

exec "${REPO_ROOT}/scripts/training/run_recogdrive_stage3_awac_iql_2b_local.sh"
