#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

export STAGE3_ALGORITHM="${STAGE3_ALGORITHM:-lfp_grpo}"
export STAGE3_OBJECTIVE="${STAGE3_OBJECTIVE:-grpo}"
export LFP_BENCHMARK="${LFP_BENCHMARK:-navsim_v1}"
: "${LFP_REFERENCE_CACHE_PATH:?Set LFP_REFERENCE_CACHE_PATH to the coherent Stage2/GT cache}"

export GRPO_SAMPLE_TIME="${GRPO_SAMPLE_TIME:-8}"
export LR="${LR:-1e-5}"
export MAX_EPOCHS="${MAX_EPOCHS:-10}"
export REFERENCE_KL_COEFF="${REFERENCE_KL_COEFF:-0.005}"
export TRAINER_GRADIENT_CLIP_VAL="${TRAINER_GRADIENT_CLIP_VAL:-1.0}"

export LFP_DDC_GT_TOLERANCE="${LFP_DDC_GT_TOLERANCE:-0.01}"
export LFP_EP_REFERENCE_TOLERANCE="${LFP_EP_REFERENCE_TOLERANCE:-0.02}"
export LFP_REFERENCE_MARGIN_WEIGHT="${LFP_REFERENCE_MARGIN_WEIGHT:-0.20}"
export LFP_REFERENCE_MARGIN_SCALE="${LFP_REFERENCE_MARGIN_SCALE:-0.05}"
export LFP_GLOBAL_STD_FLOOR="${LFP_GLOBAL_STD_FLOOR:-0.05}"
export LFP_ADVANTAGE_CLIP="${LFP_ADVANTAGE_CLIP:-3.0}"
export LFP_PARETO_GATE_ENABLED="${LFP_PARETO_GATE_ENABLED:-true}"
export LFP_PROGRESS_GATE_ENABLED="${LFP_PROGRESS_GATE_ENABLED:-true}"
export LFP_CURRICULUM_ENABLED="${LFP_CURRICULUM_ENABLED:-true}"
export LFP_CURRICULUM_WARMUP_EPOCHS="${LFP_CURRICULUM_WARMUP_EPOCHS:-1}"
export LFP_FRONTIER_FAST_EMA="${LFP_FRONTIER_FAST_EMA:-0.80}"
export LFP_FRONTIER_SLOW_EMA="${LFP_FRONTIER_SLOW_EMA:-0.98}"
export LFP_FRONTIER_PROGRESS_WEIGHT="${LFP_FRONTIER_PROGRESS_WEIGHT:-0.50}"
export LFP_FRONTIER_PRIORITY_EXPONENT="${LFP_FRONTIER_PRIORITY_EXPONENT:-0.50}"
export LFP_FRONTIER_UNIFORM_RATIO="${LFP_FRONTIER_UNIFORM_RATIO:-0.20}"
export LFP_FRONTIER_PRIORITY_QUANTILE_CAP="${LFP_FRONTIER_PRIORITY_QUANTILE_CAP:-0.95}"

# Preserve the final Stage2 PTA + FS-Norm representation exactly.
export USE_PLANNING_TOKEN_ADAPTER="${USE_PLANNING_TOKEN_ADAPTER:-true}"
export PLANNING_NUM_TOKENS="${PLANNING_NUM_TOKENS:-16}"
export PLANNING_NUM_HEADS="${PLANNING_NUM_HEADS:-8}"
export PLANNING_CONDITION_LAYERS="${PLANNING_CONDITION_LAYERS:-cross_attention}"
export PLANNING_GATE_INIT="${PLANNING_GATE_INIT:-0.05}"
export PLANNING_CONTEXT_GATE_INIT="${PLANNING_CONTEXT_GATE_INIT:-0.05}"
export PLANNING_CONDITION_DROPOUT="${PLANNING_CONDITION_DROPOUT:-0.10}"
export USE_FS_NORM="${USE_FS_NORM:-true}"
export FS_NORM_OUTPUT_CLIP_MODE="${FS_NORM_OUTPUT_CLIP_MODE:-stats_bounds}"
export FS_NORM_MIN_VERSION="${FS_NORM_MIN_VERSION:-2}"

# LFP is a single-update on-policy objective. Every legacy Stage3 mechanism is off.
export BC_ANNEAL=false
export BC_COEFF_START=0
export BC_COEFF_END=0
export GRPO_USE_GSPO_RATIO=false
export GRPO_BEHAVIOR_POLICY_SAMPLE=false
export GRPO_USE_CORE_PARETO=false
export GRPO_USE_FEASIBLE_PARETO=false
export GRPO_FP_USE_PDAS=false
export GRPO_CORE_PARETO_USE_PHENOTYPE_BUCKET_GRPO=false
export GRPO_CORE_PARETO_USE_ADAPTIVE_DUAL=false
export GRPO_CORE_PARETO_BUFFER_BONUS_ENABLED=false
export GRPO_USE_DYNAMIC_GROUP_WEIGHT=false
export GRPO_USE_DIVERSITY_REWARD=false
export OFFLINE_RL_ENABLED=false
export GRPO_BUFFER_GUIDANCE_ENABLED=false
export GRPO_BUFFER_REWARD_BONUS_WEIGHT=0
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT=0
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT_START=0
export GRPO_BUFFER_DISTILL_LOSS_WEIGHT_END=0
export GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT=0
export GRPO_BUFFER_PREFERENCE_DPO_LOSS_WEIGHT_START=0
export GRPO_SELF_IMITATION_LOSS_WEIGHT=0
export GRPO_SELF_IMITATION_LOSS_WEIGHT_START=0
export GRPO_SELF_IMITATION_LOSS_WEIGHT_END=0
export OFFLINE_RL_BC_LOSS_WEIGHT=0
export OFFLINE_RL_BC_LOSS_WEIGHT_START=0
export OFFLINE_RL_BC_LOSS_WEIGHT_END=0
export X0_AUX_WEIGHT=0
export DELTA_AUX_WEIGHT=0
export GEO_AUX_WEIGHT=0
export TRAJECTORY_AUX_WEIGHT=0
export FEASIBILITY_AUX_WEIGHT=0

# LFP has no separate validation objective; evaluation is performed from saved checkpoints.
export LIMIT_VAL_BATCHES="${LIMIT_VAL_BATCHES:-0}"
export CACHE_TRAIN_ALL_RECORDS="${CACHE_TRAIN_ALL_RECORDS:-true}"

export RUN_NAME="${RUN_NAME:-stage3_lfp_grpo_v1_$(date -u +%Y%m%dT%H%M%SZ)}"
exec "${REPO_ROOT}/scripts/training/run_recogdrive_stage3_rl_2b_local.sh" "$@"
