#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

: "${FS_NORM_STATS_PATH:?set FS_NORM_STATS_PATH to scene-balanced v2 statistics}"

export HYDRA_EXPERIMENT="${HYDRA_EXPERIMENT:-pta_fs_dit_stage2_103k}"
export USE_FS_NORM=true
export USE_PLANNING_TOKEN_ADAPTER="${USE_PLANNING_TOKEN_ADAPTER:-true}"
export PLANNING_NUM_TOKENS="${PLANNING_NUM_TOKENS:-16}"
export PLANNING_NUM_HEADS="${PLANNING_NUM_HEADS:-8}"
export PLANNING_CONDITION_LAYERS="${PLANNING_CONDITION_LAYERS:-cross_attention}"
export PLANNING_GATE_INIT="${PLANNING_GATE_INIT:-0.05}"
export PLANNING_CONTEXT_GATE_INIT="${PLANNING_CONTEXT_GATE_INIT:-0.05}"
export PLANNING_CONDITION_DROPOUT="${PLANNING_CONDITION_DROPOUT:-0.10}"
export TRAJECTORY_AUX_WEIGHT="${TRAJECTORY_AUX_WEIGHT:-0.05}"
export FEASIBILITY_AUX_WEIGHT="${FEASIBILITY_AUX_WEIGHT:-0.01}"
export AUX_ALPHA_POWER="${AUX_ALPHA_POWER:-1.0}"
export AUX_WARMUP_EPOCHS="${AUX_WARMUP_EPOCHS:-10}"
export TANGENT_MARGIN_RAD="${TANGENT_MARGIN_RAD:-0.08}"
export CURVATURE_MARGIN="${CURVATURE_MARGIN:-0.05}"
export MIN_SEGMENT_LENGTH="${MIN_SEGMENT_LENGTH:-0.20}"
export X0_AUX_WEIGHT=0.0
export DELTA_AUX_WEIGHT=0.0
export GEO_AUX_WEIGHT=0.0

exec "${REPO_ROOT}/scripts/training/run_sg_fps_asmi_stage2_103k.sh"
