"""Render the complete report only after every required experiment and audit exists."""
from common_v3 import *
from report_tables import markdown_table
REPORT=ROOT/'reports/PC_MTS_POLICY_DIAGNOSTICS_V3_20260913.md'
def tab(d,cols=None):
    if cols is not None:d=d[cols]
    return markdown_table(d)
def main():
    assert (OUT/'manifests/audit_final.json').exists()
    a=pd.read_csv(OUT/'metrics/A_pool_summary.csv');ap=pd.read_csv(OUT/'metrics/A_scene_paired_bootstrap.csv');res=pd.read_csv(OUT/'metrics/A_rescued_candidates.csv');gate=pd.read_csv(OUT/'metrics/A_pure_gate_order.csv');b=pd.read_csv(OUT/'metrics/B_key_results.csv');tax=pd.read_csv(OUT/'metrics/B_frontier_bootstrap.csv');c=pd.read_csv(OUT/'metrics/C_paired_bootstrap.csv');cp=c[(c.protocol=='primary')&(c.near_region=='all')];fe=pd.read_csv(OUT/'metrics/C_fixed_effects.csv');d=pd.read_csv(OUT/'metrics/D_matched_bootstrap.csv');dg=pd.read_csv(OUT/'metrics/D_method_bootstrap.csv');e=pd.read_csv(OUT/'metrics/E_seed_means.csv');ep=pd.read_csv(OUT/'metrics/E_final_paired.csv');f=pd.read_csv(OUT/'metrics/F_seed_means.csv');fp=pd.read_csv(OUT/'metrics/F_final_paired.csv');eff=pd.read_csv(OUT/'metrics/F_efficiency_paired.csv');g=pd.read_csv(OUT/'metrics/G_promotion_bootstrap.csv');leak=read(OUT/'manifests/audit_split_provenance.json');old=pd.read_csv(OUT/'metrics/A_original_V2_qualification.csv');overlap=pd.read_csv(OUT/'metrics/A_quality_only_overlap.csv')
    fgt=eff[(eff.method=='gt_only')&(eff.metric=='gain_per_100_steps')].iloc[0];f_safe=fp[(fp.method=='gt_only')&(fp.metric=='feasible_rate')].iloc[0];f_quality=fp[(fp.method=='gt_only')&(fp.metric=='PDMS')].iloc[0]
    seed_gains=pd.read_csv(OUT/'metrics/F_seed_gain_means.csv');sg=seed_gains.pivot(index='seed',columns='method',values='gain_per_100_steps');seed_deltas=sg.conditional_pc-sg.gt_only
    fstatus='SUPPORTED' if fgt.ci_low>0 and f_safe.ci_low>=0 and f_quality.ci_low>=0 and (seed_deltas>0).all() else 'PARTIALLY SUPPORTED' if fgt.ci_low>0 else 'NOT SUPPORTED'
    null=pd.read_csv(OUT/'metrics/G_promotion_vs_null.csv');gn=null[(null.scope=='holdout-300')&(null.metric=='promotion_minus_null')&null.run.str.startswith('grpo_final')]
    assert len(gn)==2 and set(sg.index)==set(CFG['training']['seeds']), 'Both prespecified seeds must be reported'
    gstatus='SUPPORTED' if (gn.ci_low>0).all() and (sg.conditional_pc>0).all() else 'PARTIALLY SUPPORTED' if (gn['mean']>0).any() else 'NOT SUPPORTED'
    cstatus='SUPPORTED' if all(cp[cp.metric.isin(['diffusion_loss','E_rec'])].cluster_ci_low>0) and all(fe[fe.predictor=='r_knn'].ci_low>0) else 'PARTIALLY SUPPORTED'
    conflict=d[d.metric=='cosine'].iloc[0];dstatus='SUPPORTED' if conflict.cluster_ci_high<0 else 'NOT SUPPORTED'
    text=[]
    def add(s=''):text.append(s)
    add('# PC-MTS V3：机制与受控因果诊断');add();add('本报告保留支持和失败结果。V1/V2 未被替换。V3 的 192-candidate reservoir 是分析专用的 controlled diagnostic space，**不是历史训练数据**。本轮完成 A–G、两 seed Micro-SFT、两 seed 短程 original-GRPO 和 progressive-support 分析；不把静态兼容性关联直接写成下游优化的因果保证。');add()
    add(f'分支：`analysis/pc-mts-policy-diagnostics-v3-20260913`；base commit：`{CFG["base_commit"]}`。主配置 SHA256：`{sha(CONFIG_PATH)}`。全部相对输出路径以 `outputs/pc_mts_diagnostics_v3/` 为根。')
    add('V1/V2原始观察保持不变：IL pairwise ADE约0.1448，MTS-86.92/87.51约0.0841/0.0835，GRPO/APR约0.1705/0.1831。这些历史checkpoint不是严格matched causal chain。V3通过相同初始化、相同训练预算与真实短程更新检验机制，而不是改写“Multi-SFT更窄、GRPO/APR更宽”的旧数据。')
    add('\n## 1. 预先固定的设计与数据边界\n')
    add('1000 个原始场景、每场景 192 条原始候选；split 在新训练前按 token hash 固定为 700 train / 300 diagnostic holdout。两个 seed 为 1701、2903。Micro-SFT 200 updates，保存 0/20/100/200；GRPO 100 updates，保存 0/10/50/100。每个快照在全部 300 holdout scenes 上生成相同的 64 条 CRN 随机 rollout。官方 IL step0 只生成一次并共享缓存；没有重复计算 V1 五 checkpoint 的 1000×64。')
    add('这里的PDMS是固定内部场景上的64-rollout平均，不能与历史checkpoint名称中的86.92、90.41或91.45直接作分数升降比较；那些名称保留历史权重身份，本轮分母与评测采样方式不同。')
    add(f'**不能称为完全无泄漏的独立测试集。** 新训练未使用 holdout token 更新权重，但 {leak["holdout_scenes_sharing_a_train_log"]}/300 个 holdout scenes 与训练 scenes 共享 log（共 {leak["overlapping_logs"]} 个重叠 logs）；历史 checkpoint 可能已在这些 Navtrain scenes 上训练。冻结的 V1 GT-distance 阈值也曾利用完整 1000 场景的 GT-distance 校准，包括后来划入 V3 holdout 的 300 场景。为保持 frozen baseline，没有重校准阈值。该实验是新更新之外的内部机制诊断，不是 untouched Navtest，也不支持 SOTA 或外部泛化结论。')
    add('核心差值采用至少 3000 次 scene-paired bootstrap；匹配候选同时报告 pair-level 和 scene-cluster bootstrap。固定效应回归使用 scene 与 exact-source FE，3000 次 wild scene-cluster bootstrap；不以 pooled correlation 为主要证据。训练结果先在每个 scene 内平均两个 seeds，再做 scene-paired inference，并单独公开每个 seed；两 seeds 不能充分估计训练随机性总体。另报告 log-cluster 敏感性。')
    add('表中的win_fraction/scene_win_fraction统一表示所注明差值大于0的比例；对于loss、interference或failure等指标，正差值并不等于更好。所有区间均为逐项95%区间，没有把大量指标中的偶然显著值当作统一成功判据。')
    add('\n## 2. PC-MTS-Conditional 的实际实现\n')
    add('顺序为 hard safety/validity → q<95 compatibility → PDMS quality floor → selection-local gate → compatible set 内重新计算 Pareto → Boundary 优先 → diversity tie-break。hard safety 只要求 NC=DAC=1；local gate 是四个已有 light probes 中 NC/DAC/TTC/DDC 全部满足的比例≥0.75。strict floor 为 PDMS≥reference；secondary 才允许 reference−1。q 为独立 Q→R 校准的 KNN 距离经验秩，不是概率或 likelihood。连续 d_CR、r_knn、maha_ratio 全部保留。')
    add('这里的behavioral support是有限rollout bank下的操作性诊断；Far表示几何校准分布的尾部，**不表示模型概率为0或严格不可达**。同理，原生epsilon MSE不是直接报告的trajectory likelihood。')
    add('Boundary 为 50≤q<95，先按 conditional front 再按 PDMS 与小于 0.01 point 的质量并列项中的多样性选择；Boundary 不足时用最靠近边界的 Core。Conditional primary 遍历所有 conditional fronts，不沿用 global Front≤2 的硬截断。仅改变 Front≤2 的计算位置的纯 gate-order 对照单独报告，不能把完整新 selector 的全部覆盖收益归因于 gate order。')
    add('分析池禁止 tiny/exact-duplicate 填充，只计 unique raw parents。Old-PC 的原 16-slot baseline 保持只读，主比较剔除其非 raw filler；原始 16-slot 与原算法资格统计另外保留。训练需要 16 slots 时，slot loss 权重为 `1/(U × multiplicity(parent))`，每个 unique parent 总权重等于 `1/U`。零 parent 场景显式使用 GT 训练 fallback，绝不计作 strict PC 成功。')
    add('\n## 3. Experiment A — Gate-order counterfactual\n')
    add(tab(a,['method','strict_candidate_count','unique_candidate_count','zero_strict_scene','scene_has_4','scene_has_8','scene_has_16','secondary_count','PDMS']))
    add('这里 strict_candidate_count 对所有方法统一指“已选 unique raw parents 中满足 V3 strict 条件的数量”；raw preselection availability 另列 strict_available_in_raw。Conditional 有 38/1000 场景没有可输出的 unique pool，40/1000 没有 strict candidate；这些场景没有从 Full-1000 coverage 统计中删除。候选 PDMS 对空池未定义，因此 Conditional 的 PDMS 均值基于 962 个非空池，不能直接与其他方法 1000 场景均值比较。')
    add(f'在相同的 962 个非空场景上，Conditional 相对各 baseline 的 PDMS 差值如下（这不是挑选获胜场景，而是对未定义的空池质量明确给出可比较分母；Full-1000 覆盖仍完整报告）：\n\n'+tab(ap[ap.metric=='PDMS'],['method','n','mean','median','ci_low','ci_high','win_fraction']))
    add(f'共 **{len(res)}** 条 rescued candidates，涉及 **{res.token.nunique()}/1000** 场景；far-dominator poisoning rate 为 **{res.far_dominator_poisoning.mean():.1%}**。每条 rescued candidate 的完整 dominator set 保存于 `metrics/A_rescued_dominators.parquet`。它证明了全局 gate 的过滤行为，不单独证明被排除者一定能改善训练。')
    add(f'保持 V2 其他 eligibility 条件不变，只替换 Pareto rank 计算集合时，平均 Front≤2 可用数从 **{gate.global_front2.mean():.5f}** 变为 **{gate.conditional_front2.mean():.5f}**。完整 Conditional 还取消了只允许前两层的硬截断，并采用新的 hard safety/quality 规则，因此其 16-parent coverage 变化不是纯 gate-order 效应。')
    add(f'原 V2 的 zero-qualified-parent scenes 仍为 **{old.original_V2_zero_qualified.sum()}/1000**；不要与本表对其 fallback raw parent 使用统一 V3 条件复核后的零 strict 比例混淆。原始 V2 qualification 与 filler 数量在 `A_original_V2_qualification.csv`。')
    add(f'**Pareto degeneration：** strict compatible eligibility 内 TTC、DDC 都恒为 1。目标未被替换，但排名几乎只剩 EP。quality-ranking-only 消融与 Conditional 的平均 parent-set Jaccard 为 **{overlap.Jaccard.mean():.6f}**，完全相同的场景比例为 **{overlap.identical.mean():.1%}**。因此本轮不支持多目标 Pareto 本身具有独立贡献。')
    add('\n## 4. Experiment B — Quality–Compatibility Frontier\n')
    add('直接遍历 raw reservoir；primary feasible 要求 NC/DAC/TTC/DDC 全为 1，另报告仅 NC/DAC 的 sensitivity。top-k 固定 k=4，不足4时不伪造 top4 均值。q阈值100包含全部候选，其余阈值使用严格小于。retained oracle quality 与 tax 在存在可行候选的场景上计算，coverage 则始终以全部1000场景为分母。')
    add(tab(tax[(tax.feasibility=='conservative')&(tax.metric=='compatibility_tax')],['q_threshold','n','mean','median','P25','P50','P75','P90','ci_low','ci_high']))
    add(tab(b[b.feasibility=='conservative'],['metric','n','mean','median','ci_low','ci_high']))
    add('结果支持存在有限的 Boundary headroom，但不能把“兼容性约束几乎没有质量代价”当作前提。Full-1000 的 oracle 接近比例、空集合和 coverage 全部公开，没有事后定义成功场景。')
    add('\n## 5. Experiment C — Source/quality-matched learnability\n')
    add('primary 匹配 PDMS gap≤0.25 point：3274 对、890 scenes，其中3209对为Boundary-vs-Far，65对为Core-vs-Far。另有0.5 point sensitivity，未替换primary。匹配固定same scene、exact source、NC/DAC class，Boundary优先，最大匹配数下最小总PDMS gap，一对一无replacement。每对使用完全相同的原生timestep与epsilon。官方原生参数化是epsilon，采用原归一化与uniform integer t∈[0,99]；不虚构native x0预测头。')
    add(tab(cp,['metric','n','near_mean','far_mean','mean','median','cluster_ci_low','cluster_ci_high','scene_win_fraction']))
    add('下表回归只使用每场景预先hash抽取的8条raw candidates，共8000条；同时控制r_knn、PDMS、d_GT、scene FE和exact-source FE：\n\n'+tab(fe[fe.predictor=='r_knn'],['outcome','coefficient','ci_low','ci_high','n','scenes','sources']))
    add(f'结论：**{cstatus}**。这是控制已观测变量后的原生拟合难度证据，仍不是“距离本身造成性能下降”的完整因果识别。原有V2 E_rec/return结果保留；V3对配对候选重新使用CRN计算，以免把不同噪声结果冒充paired experiment。')
    add('\n## 6. Experiment D — Gradient compatibility\n')
    add('按固定hash分析256 scenes；参数子集是最后一个DiT block与trajectory action_decoder，共2,453,219个参数，使用exact gradients，没有sketch。各scene/method使用匹配的unique candidate count，空池显式缺失；统计的有效n随比较给出。reference为IL-native gradient +0.25×GT gradient，eta统一为1e-5。')
    add(tab(d,['metric','n','near_mean','far_mean','mean','cluster_ci_low','cluster_ci_high','scene_win_fraction']))
    add(f'更大的Far gradient norm得到支持；“Far造成更低alignment/更强reference interference”状态为 **{dstatus}**。不能把较大的gradient norm等同于有害冲突。主方法与q-region分布见 `D_method_bootstrap.csv`、`D_region_summary.csv`。')
    add('\n## 7. Experiment E — Controlled Micro-SFT\n')
    add('这是实际执行的34.3M action-head SFT；VLM observation features冻结缓存。所有方法相同official-IL初始化、AdamW、LR=1e-5、cosine schedule、effective scene batch=8、16 candidate slots、GT retention coefficient=0.25、200 optimizer updates。损失为每unique parent等总权的原生epsilon-prediction MSE，加0.25×GT原生MSE；不是权重插值或参数残差合并。GT-only自身candidate target也是GT。')
    add(tab(e[e.step==200],['method','seed','PDMS','feasible_rate','pairwise_ADE','Spread_AUC','center_shift','Hit8','IL_retention_loss','candidate_fitting_loss']))
    add('Conditional减去baseline的scene-paired final差值：\n\n'+tab(ep[ep.metric.isin(['PDMS','feasible_rate','center_shift','IL_retention_loss'])],['method','metric','mean','median','ci_low','ci_high','win_fraction']))
    add('本轮实际结果呈现quality–safety取舍：Conditional位移和IL retention loss更小，安全率高于Score/Pareto，但相对GT-only的PDMS差仅约0.014 point，区间包含0，没有证明更多quality headroom。Score/Pareto-MTS的Spread-AUC反而比GT-only更大，Conditional/Old-PC更小。因此“多候选SFT必然压缩分布”也不成立；V1的历史观察不能泛化成所有candidate selection规则的必然机制。')
    add('Full-300每个scene都参与结果；训练中zero-parent的GT fallback次数和实际source权重公开在训练审计与`S_actual_training_source_weights.csv`。IL retention loss是在固定IL-native targets上的原生diffusion loss；它与真正的holdout PDMS分开报告。CRN_policy_change_ADE是同噪声轨迹变化代理，不是KL。')
    add('\n## 8. Experiment F — Short original-GRPO causal test\n')
    add('全部6种SFT initialization、两个seeds均进入同一个original archived forward_grpo；GT-SFT→GRPO没有省略。训练reward原生权重EP/TTC/comfort=10/5/2；评测为5/5/2。所有run使用相同LR=1e-4、100 updates、group=8、effective scene batch=8、BC coefficient=0.1，以及共同冻结official-IL reference。没有引入LFP或替换advantage算法。标量reward/完整loss与batched logging hook的四场景parity通过后才启动更新。')
    add('一个解释边界：原始GRPO的training sampling std floor为0.04、noise clip为5；R/Q和diagnostic evaluation使用eval std floor 0.0001、noise clip 1。该差别对所有initialization相同且本轮没有修改。在最后denoising step，0.04 normalized std对应约1.3348 m纵向/0.84 m横向的裁剪前噪声尺度。因此evaluation-bank support并不直接等于GRPO训练探索分布；它可能限制静态compatibility对GRPO gain的预测力，这属于待进一步隔离的解释，不是事后改变recipe的理由。')
    add(tab(f[f.step==100],['method','seed','PDMS','feasible_rate','EP','NC','DAC','TTC','DDC','Spread_AUC','Hit8']))
    add('Conditional相对各baseline的gain efficiency差值（每scene配对；gain以各自SFT step0为基准）：\n\n'+tab(eff,['method','metric','mean','median','ci_low','ci_high','win_fraction']))
    add('各seed的实际gain与gain AUC：\n\n'+tab(seed_gains,['method','seed','gain_AUC','gain_per_100_steps']))
    add('关键GT-SFT→GRPO对照的final quality/safety差值：\n\n'+tab(fp[(fp.method=='gt_only')&fp.metric.isin(['PDMS','feasible_rate','hard_failure','EP','TTC','Hit8'])],['metric','mean','median','ci_low','ci_high','win_fraction']))
    add(f'对“Conditional-PC提升downstream GRPO gain且保留quality/safety tradeoff”的综合状态为 **{fstatus}**。相对GT-SFT→GRPO，gain差值 **{fgt["mean"]:.5f}** point，95% CI **[{fgt.ci_low:.5f}, {fgt.ci_high:.5f}]**；final PDMS差值 **{f_quality["mean"]:.5f}**，feasible-rate差值 **{f_safe["mean"]:.5f}**。')
    if fstatus!='SUPPORTED':add('**PC-MTS优于GT-SFT→GRPO的必要性尚未得到充分支持。** 静态更容易拟合或更小位移不能替代这个关键对照；不得只引用对Score/Pareto的结果回避GT baseline。')
    add('PIA严格定义为count(A>0且infeasible)/count(infeasible)，没有infeasible rollout时记为未定义，不能伪记为0。每个rollout的7项原始指标、reward、group、advantage与feasibility均保存。Fig6同时显示gain、feasible rate、预先指定的EP–feasible轨迹和PIA；未依据结果选择最有利safety指标。')
    snapshots=pd.read_csv(OUT/'metrics/S_all_fixed_snapshot_paired.csv')
    add('预设early=10时，Conditional相对GT-SFT→GRPO的差值如下；所有其余固定快照的配对区间也保存在`S_all_fixed_snapshot_paired.csv`，不只报告final或最好的一步：\n\n'+tab(snapshots[(snapshots.stage=='F')&(snapshots.step==10)&(snapshots.method=='gt_only')],['metric','mean','median','ci_low','ci_high','win_fraction']))
    add('\n## 9. Progressive-support diagnostic\n')
    add('对两个seed的Conditional SFT final、GRPO middle/final分别重采独立R128/Q128，在原始1000场景与完全相同192-candidate bank上重新校准。high-quality固定为raw scene PDMS的75th percentile。')
    add(tab(g[g.metric.isin(['frontier_promotion_rate','newly_eligible_PC_rate','current_reference_gain'])],['run','scope','metric','n','mean','median','ci_low','ci_high']))
    add('**补充的unchanged-policy校准对照：** 在A–E完成后、任何G measurement产生前，单独冻结`calibration_control.yaml`及其hash；未改变primary YAML、阈值、split或seed。保持official-IL权重不变，重新独立采R128/Q128，测量仅由有限bank重采样产生的q跨阈值。该对照作为新增supplementary报告，不冒称属于最初primary预注册。')
    add(tab(null[null.scope=='holdout-300'],['run','metric','n','mean','ci_low','ci_high']))
    add(f'扣除unchanged-policy turnover后，关于更强policy的frontier迁移状态为 **{gstatus}**。未定义promotion rate的场景（raw bank没有旧high-quality Far候选）仍保留scene记录，表中n明确给出可计算分母。')
    add('这只检验Far(old)→compatible(new)的support迁移。迁移可能同时包含中心移动、旧Core遗忘或support宽度改变；`S_progressive_support_retention.csv`保留这些诊断。因此即使观测到promotion，也不等于已验证compute-matched multi-round progressive PC-MTS。该更强结论为 **UNTESTED**。')
    add('\n## 10. 十个研究问题与保守论文表述\n')
    add('1. **SUPPORTED（过滤行为）**：Global-Pareto-first确实排除了compatible candidates；是否“错误”还取决于下游utility，不能仅由rescue定义推出。\n2. **PARTIALLY SUPPORTED**：strict unique覆盖明显提高；但在同一962场景上候选PDMS下降，因此“不牺牲quality”的更强说法不成立。\n3. **SUPPORTED（有限frontier）**：Boundary在部分场景有正headroom；compatibility tax和低覆盖场景同时存在。\n4. **SUPPORTED（非可替代性证据）**：控制GT-distance后r_knn仍预测原生学习难度；GT-distance与policy support不能直接等同。')
    add(f'5. **{cstatus}**：同scene/source/quality匹配与固定效应结果支持support-distance和loss/reconstruction difficulty相关。\n6. **{dstatus}**：gradient norm更大不意味着更强有害interference；alignment的区间包含零。\n7. **PARTIALLY SUPPORTED**：Micro-SFT产生明确的位移/retention差异，但quality/safety存在取舍，且实际training pools仍是source/quality/support属性的组合处理，不能把全部效应唯一归因于support distance。\n8. **{fstatus}**：统一GRPO的关键GT baseline结论见Section8，不能以step0最高替代gain证据。\n9. **{gstatus}（仅限support迁移）**：Full-1000、holdout-300与unchanged-policy null均见Section9；不宣称完成多轮训练验证。\n10. **UNTESTED（更强多轮/外部泛化结论）**：没有compute-matched多轮实验，且holdout并非独立未接触测试集。')
    add('建议论文首先表述为：“离线轨迹质量不足以刻画其对给定起始planner的监督可学习性。在受控候选空间中，policy-support兼容性提供了超出GT distance与离线分数的原生拟合难度信息；在兼容集合内排序可避免global Pareto gate过滤局部可达候选。其是否改善后续优化，需要以相同初始化预算、GT-SFT→GRPO对照及真实quality/safety结果限定。”')
    add('应放弃或暂缓：所有高分轨迹都同样适合作为监督；更大梯度必然意味着更强冲突；Pareto在本数据上必然提供独立多目标收益；兼容性约束没有质量代价；本轮静态结果已证明多轮训练有效。是否可将PC-MTS写为论文核心性能贡献，必须同时满足下游GT对照和独立基准验证，不能仅凭A–D的结果。')
    add('\n## 11. 可复核产物与审计\n')
    add('主配置、split与hash：`configs/pc_mts_diagnostics_v3/primary.yaml`、`manifests/protocol_frozen.json`、`manifests/splits.json`。原始配对、全部dominator与每scene比较均在`metrics/`，大型rollout/checkpoint保留服务器不进入git。`manifests/CACHE_INDEX.json`记录缓存/权重hash；`INITIALIZATION_TENSOR_AUDIT.json`验证实际tensor初始化一致。')
    add('数值无改动的两项实现修复已单独审计：C的query_id由object数组转换成Unicode，所有数值数组逐bit一致；A的strict_candidate_count统一计数范围，原始schema保留，parent ids、严格已选数量和全部主比较未变。没有修改阈值、alpha、split、seed、模型rollout数值或根据结果筛scene。')
    for i in range(1,8):
        name=next((OUT/'figures').glob(f'Fig-V3-{i}_*.png')).stem;add(f'Fig-V3-{i}: [PNG](../outputs/pc_mts_diagnostics_v3/figures/{name}.png) / [PDF](../outputs/pc_mts_diagnostics_v3/figures/{name}.pdf)；[绘图表](../outputs/pc_mts_diagnostics_v3/metrics/{name}_plot_data.csv)（复合图其他输入见相应A–G tables）。\n\n![Fig-V3-{i}](../outputs/pc_mts_diagnostics_v3/figures/{name}.png)')
    add('\nSUPPORTED、PARTIALLY SUPPORTED、NOT SUPPORTED、UNTESTED分别对应数据支持、有限支持、当前未获支持、尚未实际检验；NOT SUPPORTED不等于已证明普遍无效。')
    REPORT.write_text('\n\n'.join(text)+'\n');save(OUT/'manifests/report_identity.json',dict(identity=identity(),report=str(REPORT),sha256=sha(REPORT),downstream_GT_comparison_status=fstatus,learnability_status=cstatus,gradient_conflict_status=dstatus));print(REPORT,flush=True)
if __name__=='__main__':main()
